import Head from 'next/head';
import Header from '@/components/spacex/header';
import WieSpace from '@/components/spacex/weispace';
import Generation from '@/components/spacex/generation';
import Weitech from '@/components/spacex/weitech';
import WeiMong from '@/components/spacex/weimong';
import RoadMap from '@/components/spacex/roadmap';
import WeiTeam from '@/components/spacex/weiteam';

export default function Home() {
  return (
    <div className="spacex">
      <Head>
        <title>Weimong to the moon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="bg-black text-white relative z-10">
        <WieSpace />
        <Generation />
        <Weitech />
        <WeiMong />
        <RoadMap />
        <div>
          <video src="/videos/nasa.mp4" autoPlay={'autoplay'} preLoad="auto" muted className="w-full" loop></video>
        </div>
        <WeiTeam />
      </main>
    </div>
  );
}
