// import Head from 'next/head';
// import Header from '@/components/weillion/header';
// import WhiteSpaer from '@/components/weillion/white-paper';
// import Blog from '@/components/weillion/blog';
// import Infomation from '@/components/weillion/infomation';
// import GamePlayScreenShot from '@/components/weillion/screen-shot';
// import HowToPlay from '@/components/weillion/how-to-play';
// import Roadmap from '@/components/weillion/roadmap';
// import Footer from '@/components/weillion/footer';

export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>Weimong to the moon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="bg-black text-white relative z-10">
        <div className="banner">
          <video src="/videos/header.mp4" className="w-full" muted autoPlay={'autoplay'} preload="auto" loop>
            something
          </video>
        </div>
        <WhiteSpaer />
        <Blog />
        <Infomation />
        <GamePlayScreenShot />
        <HowToPlay />
        <Roadmap />
        <Footer />
      </main> */}
    </div>
  );
}
