import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weimong to the moon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black text-white relative z-10"></main>
    </div>
  );
}
